spring.application.name=mco

# TODO: remplace par tes vrais identifiants de connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mcotools
spring.datasource.username=postgres
spring.datasource.password=changeme

# validate = ne touche pas au schema existant, verifie juste qu'il correspond aux entites
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

